modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/lilypuree/WanderingTrapper/issues" #optional
[[mods]] #mandatory
modId="wandering_trapper" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wandering Trapper" #mandatory
displayURL="https://github.com/lilypuree/WanderingTrapper"
#logoFile="examplemod.png"
credits="thanks to ewewukek's musket mod, and the mmd discord"
authors="lilypuree"
description='''
This mod adds a wandering trapper that spawns like the wandering trader, but only in cold biomes.
Unlike the useless wandering trader, the trapper sells various pelts cheaply. You can resell those pelts to a
furrier villager(job block is cake, WIP), who will buy them for much more emeralds. Profit!
You can hunt foxes and polarbears for their pelts. The drop rate is very low, but it gets better as you gain experience.
Be careful when you decide to fight the trapper, he is very strong.
When you install ewewukek's musket mod, he will hold a musket!
'''

[[dependencies.wandering_trapper]]
    modId="musketmod"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="AFTER"
    side="BOTH"